server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/contacts_db
    username: postgres
    password: postgres
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  devtools:
    restart:
      enabled: true

app:
  frontendUrl: http://localhost:4200